[package]
name = "em_mutex"
version = "0.1.0"
edition = "2021"

[lib]
name = "em_mutex"
crate-type = ["staticlib"]

[dependencies]
rt-rust = { path = "../../../" }
rt_macros = { path = "../../../rt_macros/" }
