# RT-Thread building script for Rust examples

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

subdirs = ['application', 'component', 'modules']

for subdir in subdirs:
    if subdir in list:
        group = group + SConscript(os.path.join(subdir, 'SConscript'))

Return('group')