[package]
name = "rt_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# bitfield = "0.13.2"
# cfg-if = "1.0.0"
# lazy_static = "1.4.0"

[features]
default = []
# rtt = [ "lazy_static/spin_no_std",]
smp = []
