[package]
name = "em_component_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
macro_main = { path = "../../macro-main/" }
rt_rust = { path = "../../rt-rust/" }
em_component_log = { path = "../../example_component/log"}