[package]
name = "em_sem"
version = "0.1.0"
edition = "2021"

[lib]
name = "em_sem"
crate-type = ["staticlib"]

[dependencies]
rt-rust = { path = "../../rust/" }
macro_main = { path = "../../rust/macro-main/" }
