[build]
target = "riscv64gc-unknown-linux-gnu"

[unstable]
build-std = ["core", "alloc", "panic_abort"]

[target.riscv64gc-unknown-linux-gnu]
linker = "ld.lld"
rustflags = [
    "-C", "link-arg=-m", "-C", "link-arg=elf64lriscv",
    "-C", "link-arg=-L/usr/riscv64-linux-gnu/lib",
    "-C", "link-arg=-L/usr/lib/riscv64-linux-gnu",
    "-C", "link-arg=-L/usr/lib/gcc-cross/riscv64-linux-gnu/9",
    "-C", "panic=abort"
]